# Generated by Django 4.1.1 on 2024-01-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_category_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
